version: '3'
services:
  erp-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_PROFILE: ${BUILD_PROFILE:-build}
    container_name: erp-front
    ports:
      - '3000:3000'
    networks:
      - erp

networks:
  erp: {}
