version: '3'
services:
  erp-front-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_PROFILE: ${BUILD_PROFILE:-build}
    container_name: erp-front-prod-final
    ports:
      - '3007:3000'
    networks:
      - erp

networks:
  erp: {}
